#Baseline run configuration
base:
    arch_dir: ../src/models/imagenet
    workers: 4
    description: '0.2'
    train_batch: 256
    test_batch: 40
    epochs: 90
    learning-rate: 0.1
    schedule: 41,61,81
    resume: ''
    arch: resnet50_flat
    save_checkpoint: 10
    is_gating: False
# PruneTrain configuration
pt: 
    en_group_lasso: True
    var_group_lasso_coeff: 0.2
    sparse_interval: 5
    threshold: 0.0001
    reconf_arch: True
